---
title: "linear_models"
author: "AimingLiu"
date: "11/7/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## This is gonna be so great

seriously linear models
```{r}
  library(p8105.datasets)
  library(tidyverse)
  
   set.seed(1)
```

```{r}
  data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

Fit a first linear model
```{r}
 fit = lm(price ~ stars + boro,data = nyc_airbnb)
```

```{r}
 fit

 summary(fit)
 coef(fit)
 summary(fit)$coef
```
tidy the results
```{r}
  fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term,"boro","Boro:")) %>% 
  
  knitr::kable(digits = 3)

#The broom package has functions for obtaining a quick summary of the model and for cleaning up the coefficient table.
  fit %>% 
  broom::glance()
```

## Take a look at factors

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate( boro = fct_infreq(boro),
    room_type = fct_infreq(room_type))
#fct_infreq 按照出现的频率排列#
```

```{r}
refit = lm(price ~ stars + boro,data = nyc_airbnb)
# () more than manhattan#

```

## diagnostics

```{r}
 modelr::add_residuals(nyc_airbnb,fit) %>% 
  ggplot(aes(x = stars,y = resid))+
  geom_point()+
  ylim(-500,500)

modelr::add_predictions(nyc_airbnb,fit)
```

```{r}
nyc_airbnb %>% 
  lm(price ~ stars * boro + room_type * boro, data = .) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3) 
```

```{r}
nyc_airbnb %>% 
  filter(boro == "Brooklyn") %>% 
  lm(price ~ stars + room_type,data = .) %>% 
  broom::tidy()
```

let's try to map this instead
```{r}


```

